local hg = CreateFrame("Frame")
hg.values = CreateUnitHealPredictionCalculator()
hg.values:SetDamageAbsorbClampMode(Enum.UnitDamageAbsorbClampMode.MaximumHealth)
hg.values:SetHealAbsorbClampMode(Enum.UnitHealAbsorbClampMode.MaximumHealth)
hg.values:SetIncomingHealClampMode(Enum.UnitIncomingHealClampMode.MaximumHealth)
hg.values:SetHealAbsorbMode(Enum.UnitHealAbsorbMode.Total)
hg.values:SetIncomingHealOverflowPercent(1)

UnitGetDetailedHealPrediction("player", "player", hg.values)
local allHeal = hg.values:GetIncomingHeals()
print(allHeal)