state:
  锚点:    
    step: 1
    type: "bool"
  职业:   
    step: 2
    type: "int"
  专精:
    step: 3
    type: "int"
  有效性:   
    step: 4
    type: "bool"
  战斗:
    step: 5
    type: "bool"
  移动:
    step: 6
    type: "bool"
  施法:
    step: 7
    type: "int"
  引导:
    step: 8
    type: "int"
  生命值:
    step: 9
    type: "int"
  能量值:
    step: 10
    type: "int"

5:
  keymap: "priest.yml"
  1:
    一键辅助:
      step: 11
      type: "int"
    目标有效:     
      step: 12
      type: "bool"
    spells:
      真言术：盾:
        step: 15
        type: "int"
      苦修:
        step: 16
        type: "int"
      真言术：耀:
        step: 17
        type: "int"
      纯净术:
        step: 18
        type: "int"
      绝望祷言:
        step: 19
        type: "int"
      心灵震爆:
        step: 20
        type: "int"
      福音:
        step: 21
        type: "int"
      暗言术：灭:
        step: 22
        type: "int"
    虚空之盾:
      step: 23
      type: "bool"
    圣光涌动:
      step: 24
      type: "bool"
    队伍人数:
      step: 25
      type: "int"
    group:
      start: 25
      num: 5
      生命值:
        step: 1
        type: "int"
      职责:
        step: 2
        type: "int"
      驱散:
        step: 3
        type: "int"
      救赎:
        type: "int"
        step: 4
      真言术：盾:
        type: "int"
        step: 5
  3:
    一键辅助:
      step: 11
      type: "int"
    目标有效:
      step: 12
      type: "bool"
    spells:
      心灵震爆:
        step: 13
        type: "int"
      暗言术：灭:
        step: 14
        type: "int"
      虚空洪流:
        step: 15
        type: "int"
      虚空形态:
        step: 16
        type: "int"
      触须猛击:
        step: 17
        type: "int"
      绝望祷言:
        step: 18
        type: "int"